backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "home"
    label: "Page d'accueil"
    files:
      - name: "home"
        label: "Contenu accueil"
        file: "content/home.json"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Texte", name: "text", widget: "text" }

          - label: "Promo"
            name: "promo"
            widget: "object"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Texte", name: "text", widget: "text" }

          - label: "Carousel"
            name: "carousel"
            widget: "list"
            required: false

            field: { label: "Image", name: "image", widget: "image" }
