backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "home"
    label: "Accueil â€“ Carrousel"
    files:
      - name: "home"
        label: "Images du carrousel"
        file: "content/home.json"
        format: "json"
        fields:
          - label: "Carrousel"
            name: "carousel"
            widget: "list"
            allow_add: true
            summary: "{{fields.image}}"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
