backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "homepage"
    label: "Page dâ€™accueil"
    files:
      - file: "admin/content/homepage.json"
        label: "Contenu accueil"
        name: "homepage"
        fields:
          - { label: "Titre hero", name: "hero_title", widget: "string" }
          - { label: "Texte hero", name: "hero_text", widget: "text" }
