backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "carousel"
    label: "Carousel (Accueil)"
    files:
      - name: "carousel"
        label: "Images du carousel"
        file: "content/home.json"
        fields:
          - label: "Images"
            name: "carousel"
            widget: "list"
            allow_add: true
            field:
              label: "Image"
              name: "image"
              widget: "image"
