backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "site"
    label: "Contenu du site"
    files:
      - name: "homepage"
        label: "Page dâ€™accueil"
        file: "content/homepage.json"
        fields:
          - { label: "Titre hero", name: "hero_title", widget: "string" }
          - { label: "Texte hero", name: "hero_text", widget: "text" }
          - { label: "Image hero", name: "hero_image", widget: "image" }
